---
- name: create rootless group
  ansible.builtin.group: 
    name: "{{ docker_rootless.group }}"
    state: present
  become: true

- name: create user
  ansible.builtin.user:
    name: "{{ item.user }}" 
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    create_home: true
    shell: /bin/bash
    state: present
  loop: "{{ users_dict }}"
  become: true

- name: apply subid/subgid mappings
  ansible.builtin.template:
    src: subid.j2
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  loop:
    - subuid
    - subgid
  become: true

- name: disable root docker daemon 
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - docker.service
    - docker.socket
  ignore_errors: true
  become: true

- name: Enable linger
  ansible.builtin.command: "loginctl enable-linger {{ item.user }}"
  changed_when: false
  loop: "{{ users_dict }}"
  become: true

- name: Debug subuid/subgid content
  ansible.builtin.command: "grep {{ item.user }} /etc/subuid /etc/subgid"
  loop: "{{ users_dict }}"
  changed_when: false
  ignore_errors: true
  register: subid_check

- name: Show subuid/subgid debug
  ansible.builtin.debug:
    var: subid_check.results

- name: install rootless docker
  become_user: "{{ item.user }}"
  ansible.builtin.shell: |
    export XDG_RUNTIME_DIR="/run/user/{{ item.uid }}"
    export PATH=/usr/bin:$PATH
    dockerd-rootless-setuptool.sh install -f
  loop: "{{ users_dict }}"
  args:
    creates: "/home/{{ item.user }}/.config/systemd/user/docker.service"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ item.uid }}"

- name: Export docker socket
  become_user: "{{ item.user }}"
  ansible.builtin.lineinfile:
    path: "/home/{{ item.user }}/.bashrc"
    line: 'export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock'
    create: true
  loop: "{{ users_dict }}"
  
# остановился на том, что экспортировал runtime,
#  по логу, он экспортировался, но всё равно не может
  # он запустить от имени docker, почему, идей пока что нет,
  #  нужно наверное вывод посмотреть, потому что я сделал всё,
    # как руками я создавал до этого момента.
    #  Экспорт сокета происходит в следующем шаге 

    